name: Node.js CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clear npm cache and install dependencies
      run: |
        npm cache clean --force
        npm install
    - name: Set up environment variables
      run: echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> $GITHUB_ENV
    - name: Run Tests
      run: npm test
      env:
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
